### ISSUE TITLE
IllegalStateException in HTTP 1.0-RC2 client with pipelining enabled

### ISSUE THREAD

**Issue by egisj** [akka/akka#17521]
Given this server implementation:
```scala
object TestServer extends App with Directives {
  implicit val system = ActorSystem()
  implicit val flowMaterializer = ActorFlowMaterializer()

  val requestHandler: HttpRequest => HttpResponse = {
    _ => HttpResponse()
  }

  val serverSource = Http().bind("localhost", 8080)

  serverSource.to(Sink.foreach { connection =>
    connection handleWithSyncHandler requestHandler
  }).run()
}
```

And this client:
```scala
object BugDemo extends App {
  implicit val actorSystem = ActorSystem()
  implicit val flowMaterializer = ActorFlowMaterializer()

  val http = Http()
  val req = HttpRequest(HttpMethods.GET, "http://localhost:8080")

  (1 to 100000).foreach { _ => http.singleRequest(req) }
}
```
I often get the following exception:
```
[ERROR] [05/19/2015 13:03:59.045] [default-akka.actor.default-dispatcher-15] [akka://default/user/$a/flow-5-0-actorPublisherSource-actorPublisherSource] onNext is not allowed when the stream has not requested elements, totalDemand was 0
java.lang.IllegalStateException: onNext is not allowed when the stream has not requested elements, totalDemand was 0
	at akka.stream.actor.ActorPublisher$class.onNext(ActorPublisher.scala:190)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.onNext(PoolSlot.scala:193)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor$$anonfun$receive$1.applyOrElse(PoolSlot.scala:197)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.akka$stream$actor$ActorPublisher$$super$aroundReceive(PoolSlot.scala:193)
	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:317)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.aroundReceive(PoolSlot.scala:193)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Looks like it happens only if pipelining is enabled. I cannot reproduce it all the time, but setting the pipelining limit to fairly high value seems to trigger this behaviour. For example, with the following settings, I get the exception every time I run the above client:
```
akka.http.host-connection-pool {
  max-connections = 10
  pipelining-limit = 15
  max-open-requests = 16384
}
```

**Comment by sirthias** [comment]
I just added a test trying to reproduce the problem:
https://github.com/spray/akka/commit/37b9bb5a9be6ac761b7827d2fdb9282f00ff5383

Unfortunately the test is green, no matter how large I set `N`.
Even with 100,000 requests everything still runs smoothly.

@egisj Could you try upgrading to RC3 and see whether the problem is still present for you?

**Comment by egisj** [comment]
Hi,

I upgraded to RC3 and can still see the problem. The exact code and settings I am running are here: https://github.com/egisj/akka-http-pipelining-bug

**Comment by ale64bit** [comment]
I detected a similar behavior with the same scenario under RC3 using only the client side: requesting many times very often with pipelining enabled (and as low as 4) causes the above exception often.

**Comment by drewhk** [comment]
Yes, I think this has been fixed. @sirthias ?

**Comment by sirthias** [comment]
I'm not sure what exactly fixed this, as I don't know what originally caused the problem.
Might be a fix in the streams layer as well.
Anyway, if the OP can't reproduce either I'd vote for closing (and maybe reopening later).

**Comment by drewhk** [comment]
We fixed much :)

**Comment by egisj** [comment]
Just upgraded to RC4 and the issue is still there:
```
[ERROR] [06/26/2015 14:50:57.597] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a/flow-2-0-actorPublisherSource-actorPublisherSource] onNext is not allowed when the stream has not requested elements, totalDemand was 0
java.lang.IllegalStateException: onNext is not allowed when the stream has not requested elements, totalDemand was 0
	at akka.stream.actor.ActorPublisher$class.onNext(ActorPublisher.scala:182)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.onNext(PoolSlot.scala:209)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor$$anonfun$receive$1.applyOrElse(PoolSlot.scala:213)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.akka$stream$actor$ActorPublisher$$super$aroundReceive(PoolSlot.scala:209)
	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:309)
	at akka.http.impl.engine.client.PoolSlot$FlowInportActor.aroundReceive(PoolSlot.scala:209)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by drewhk** [comment]
Btw, shouldn't the responses entity be consumed?

**Comment by romansky** [comment]
I can reproduce the issue using @drewhk repo, is it used wrong or is there some other reason the issue persists?
