### ISSUE TITLE
HttpServerBluePrint: Cannot pull closed port

### ISSUE THREAD

**Issue by kstokoz** [akka/akka#20869]
Occasionally after client cancel upload of file and stream is interrupted with 
```
akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$chunkedEntity$1$$anonfun$2.applyOrElse(HttpMessageParser.scala:349)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$chunkedEntity$1$$anonfun$2.applyOrElse(HttpMessageParser.scala:347)
	at akka.stream.impl.fusing.Collect$$anon$2$$anonfun$4.apply(Ops.scala:177)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:144)
	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:179)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
```
 i see following exception:
```
[akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@6d6c6596]: requirement failed: Cannot pull closed port (requestParsingIn)
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (requestParsingIn)
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:346)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$15.onPush(HttpServerBluePrint.scala:427)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
```

**Comment by ktoso** [comment]
Thanks for reporting, would you be able to provide a reproducer?
What Akka version and what client are you using?

**Comment by kstokoz** [comment]
We are using akka 2.4.6, I can try to see if i will be able to have a reproducer for this.

Sometimes after same stream interruption we see 

```
[akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@2f77ea9]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:435)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:393)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
	
```
which i think was fixed in other ticket.

**Comment by ktoso** [comment]
Yes, the double push I believe I fixed last week. The double pull also surfaced in another ticket, but we don't have a reproducer yet which makes debugging hard. It would be great if you could minimise the problem into a reproducer, thanks in advance!

**Comment by johanandren** [comment]
Probably fixed by the fix for #21008

**Comment by johanandren** [comment]
(The `Cannot pull closed port (requestParsingIn)` that is) It got merged in 2.4.9-RC1, so please try that and see if you can reproduce.

**Comment by johanandren** [comment]
I think the `Cannot push port (requestPrepOut) twice` is not fixed however. Looking into it.

**Comment by johanandren** [comment]
Ok, that was also recently fixed in #20789

I'll close this ticket, please re-open (or open new tickets) if it the same errors are seen in 2.4.9RC1 and later.
